baseURL: "https://phys-e.gitlab.io"
languageCode: ru
theme: stack
paginate: 5
title: "Материалы по пракам"

languages:
  ru:
    languageName: Русский
    weight: 1

DefaultContentLanguage: ru

permalinks:
  book: /b/:filename/
  pe: /pe/:filename/
  page: /:filename/

params:
  mainSections:
    - book
    - pe
  featuredImageField: image
  rssFullContent: true
  # favicon:

  footer:
    since: 2022
    # customText:

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
    # emoji: 🦜
    subtitle: "Olphys"
    avatar:
      enabled: false
      # local: true
      # src: img/avatar.png

  article:
    math: false
    toc: true
    readingTime: false
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # site:
      card: summary_large_image

  # defaultImage:
  #   opengraph:
  #     enabled: false
  #     local: false
  #     src:

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main: []

  # social:
    # - identifier: github
      # name: GitHub
      # url: https://github.com/averyanalex
      # params:
        # icon: brand-github

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  # goldmark:
  #   renderer:
  #     ## Set to true if you have HTML content inside Markdown
  #     unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
